server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 避免 swagger 报错
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认600000即5分钟
      max-lifetime: 600000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  aop:
    proxy-target-class: true
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: "cache:"
      time-to-live: 60000
  redis:
    host: 127.0.0.1 #Redis地址
    database: 0 #Redis数据库索引
    port: 6379 #Redis端口
    password: #Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）

#pagehelper:
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql

mybatis-plus:
  mapper-locations: classpath:org/unknown100name/ecommerce/dao/xml/*Mapper.xml, classpath:org/unknown100name/ecommerce/recommend/dao/xml/*Mapper.xml
  type-aliases-package: org.unknown100name.ecommerce.pojo.entity.org.unknown100name.ecommerce.recommend.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      db-type: mysql

mybatis:
  mapper-locations: classpath:org/unknown100name/ecommerce/dao/xml/*Mapper.xml, classpath:org/unknown100name/ecommerce/recommend/dao/xml/*Mapper.xml