server:
  port: 8082

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 避免 swagger 报错
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/ecommerce?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      test-on-borrow: true
      test-while-idle: true
      hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认600000即5分钟
      max-lifetime: 600000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  aop:
    proxy-target-class: true

mybatis-plus:
  mapper-locations: classpath:org/unknown100name/ecommercerecommend/dao/xml/*Mapper.xml
  type-aliases-package: org.unknown100name.ecommercerecommend.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      db-type: mysql

mybatis:
  mapper-locations: classpath:org/unknown100name/ecommercerecommend/dao/xml/*Mapper.xml